-- ============================================================================
-- Source: database/35_product_types_master.sql
-- ============================================================================

-- Maestro de tipos de producto para empresas en modo pedido.
-- Incluye:
-- 1) Tabla public.product_types por empresa.
-- 2) Vinculo opcional services.product_type_id.
-- 3) Migracion de nombres legacy tipo::producto.
-- 4) RPCs admin para listar/guardar/eliminar tipos.
-- 5) save_admin_service actualizado para persistir product_type_id.

begin;

create table if not exists public.product_types (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_types_name_not_blank_chk check (length(trim(name)) > 0)
);

create unique index if not exists product_types_company_name_uidx
  on public.product_types(company_id, lower(trim(name)));

create index if not exists product_types_company_active_idx
  on public.product_types(company_id, active);

drop trigger if exists product_types_set_updated_at on public.product_types;
create trigger product_types_set_updated_at
before update on public.product_types
for each row execute function public.set_updated_at();

alter table if exists public.services
  add column if not exists product_type_id bigint;

alter table if exists public.services
  drop constraint if exists services_product_type_id_fkey;
alter table if exists public.services
  add constraint services_product_type_id_fkey
  foreign key (product_type_id) references public.product_types(id) on delete set null;

create index if not exists services_product_type_id_idx
  on public.services(product_type_id);

-- Migra tipos existentes del formato "tipo :: producto" en empresas modo pedido.
insert into public.product_types (company_id, name, active)
select distinct
  services.company_id,
  trim(split_part(services.name, '::', 1)) as product_type_name,
  true
from public.services services
join public.app_configuration config
  on config.company_id = services.company_id
where services.company_id is not null
  and position('::' in services.name) > 0
  and trim(split_part(services.name, '::', 1)) <> ''
  and (
    coalesce(config.modo_operacion, 'turno') = 'pedido'
    or config.usa_agenda = false
  )
on conflict (company_id, lower(trim(name))) do nothing;

update public.services services
set product_type_id = product_types.id
from public.product_types product_types
join public.app_configuration config
  on config.company_id = product_types.company_id
where services.company_id = product_types.company_id
  and services.product_type_id is null
  and position('::' in services.name) > 0
  and lower(trim(split_part(services.name, '::', 1))) = lower(trim(product_types.name))
  and (
    coalesce(config.modo_operacion, 'turno') = 'pedido'
    or config.usa_agenda = false
  );

alter table public.product_types enable row level security;

drop policy if exists "product_types_admin_read" on public.product_types;
create policy "product_types_admin_read"
on public.product_types for select
using (public.is_admin());

drop policy if exists "product_types_admin_insert" on public.product_types;
create policy "product_types_admin_insert"
on public.product_types for insert
with check (public.is_admin());

drop policy if exists "product_types_admin_update" on public.product_types;
create policy "product_types_admin_update"
on public.product_types for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "product_types_admin_delete" on public.product_types;
create policy "product_types_admin_delete"
on public.product_types for delete
using (public.is_admin());

grant select on public.product_types to authenticated;
grant insert, update, delete on public.product_types to authenticated;

create or replace function public.get_admin_product_types(
  account_id_value uuid default null,
  session_token_value text default null,
  company_slug_value text default null
)
returns table (
  id bigint,
  name text,
  active boolean,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  admin_account public.internal_accounts%rowtype;
  target_company_id uuid;
begin
  admin_account := public.validate_internal_session(account_id_value, session_token_value, 'admin'::public.app_role);
  target_company_id := coalesce(public.get_company_id_by_slug(company_slug_value), admin_account.company_id);

  if target_company_id is null then
    raise exception 'La empresa no esta disponible.';
  end if;

  if admin_account.company_id is distinct from target_company_id then
    raise exception 'No podes administrar otra empresa.';
  end if;

  return query
  select
    product_types.id,
    product_types.name,
    product_types.active,
    product_types.created_at,
    product_types.updated_at
  from public.product_types
  where product_types.company_id = target_company_id
  order by lower(trim(product_types.name)), product_types.id;
end;
$$;

create or replace function public.save_admin_product_type(
  product_type_id_value bigint default null,
  name_value text default null,
  active_value boolean default true,
  account_id_value uuid default null,
  session_token_value text default null,
  company_slug_value text default null
)
returns table (
  id bigint,
  name text,
  active boolean,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  admin_account public.internal_accounts%rowtype;
  target_company_id uuid;
  clean_name text := nullif(trim(coalesce(name_value, '')), '');
  previous_name text;
  existing_product_type_id bigint;
begin
  admin_account := public.validate_internal_session(account_id_value, session_token_value, 'admin'::public.app_role);
  target_company_id := coalesce(public.get_company_id_by_slug(company_slug_value), admin_account.company_id);

  if target_company_id is null then
    raise exception 'La empresa no esta disponible.';
  end if;

  if admin_account.company_id is distinct from target_company_id then
    raise exception 'No podes administrar otra empresa.';
  end if;

  if clean_name is null then
    raise exception 'Ingresa un nombre para el tipo de producto.';
  end if;

  if product_type_id_value is null then
    select product_types.id
    into existing_product_type_id
    from public.product_types
    where product_types.company_id = target_company_id
      and lower(trim(product_types.name)) = lower(trim(clean_name))
    limit 1;

    if existing_product_type_id is null then
      return query
      insert into public.product_types (company_id, name, active)
      values (target_company_id, clean_name, coalesce(active_value, true))
      returning product_types.id, product_types.name, product_types.active, product_types.created_at, product_types.updated_at;

      return;
    end if;

    return query
    update public.product_types
    set name = clean_name,
        active = coalesce(active_value, true)
    where product_types.id = existing_product_type_id
      and product_types.company_id = target_company_id
    returning product_types.id, product_types.name, product_types.active, product_types.created_at, product_types.updated_at;

    return;
  end if;

  select product_types.name
  into previous_name
  from public.product_types
  where product_types.id = product_type_id_value
    and product_types.company_id = target_company_id;

  if previous_name is null then
    raise exception 'El tipo de producto no pertenece a esta empresa.';
  end if;

  return query
  update public.product_types
  set name = clean_name,
      active = coalesce(active_value, true)
  where product_types.id = product_type_id_value
    and product_types.company_id = target_company_id
  returning product_types.id, product_types.name, product_types.active, product_types.created_at, product_types.updated_at;

  -- Si cambia el nombre del tipo, actualiza nombres legacy tipo::producto.
  if previous_name is distinct from clean_name then
    update public.services
    set name = concat(clean_name, ' :: ', trim(substring(public.services.name from '::(.*)$')))
    where public.services.company_id = target_company_id
      and position('::' in public.services.name) > 0
      and lower(trim(split_part(public.services.name, '::', 1))) = lower(trim(previous_name));
  end if;
end;
$$;

create or replace function public.delete_admin_product_type(
  product_type_id_value bigint,
  account_id_value uuid default null,
  session_token_value text default null,
  company_slug_value text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  admin_account public.internal_accounts%rowtype;
  target_company_id uuid;
  current_type_name text;
begin
  admin_account := public.validate_internal_session(account_id_value, session_token_value, 'admin'::public.app_role);
  target_company_id := coalesce(public.get_company_id_by_slug(company_slug_value), admin_account.company_id);

  if target_company_id is null then
    raise exception 'La empresa no esta disponible.';
  end if;

  if admin_account.company_id is distinct from target_company_id then
    raise exception 'No podes administrar otra empresa.';
  end if;

  select product_types.name
  into current_type_name
  from public.product_types
  where product_types.id = product_type_id_value
    and product_types.company_id = target_company_id;

  if current_type_name is null then
    raise exception 'El tipo de producto no pertenece a esta empresa.';
  end if;

  if exists (
    select 1
    from public.services
    where services.company_id = target_company_id
      and (
        services.product_type_id = product_type_id_value
        or (
          position('::' in services.name) > 0
          and lower(trim(split_part(services.name, '::', 1))) = lower(trim(current_type_name))
        )
      )
  ) then
    raise exception 'No se puede eliminar un tipo con productos asociados.';
  end if;

  delete from public.product_types
  where product_types.id = product_type_id_value
    and product_types.company_id = target_company_id;
end;
$$;

-- save_admin_service con product_type_id opcional (mantiene compatibilidad por defaults).
create or replace function public.save_admin_service(
  service_id_value bigint,
  name_value text,
  icon_value text,
  color_value text,
  default_duration_value integer,
  base_price_value numeric,
  active_value boolean,
  account_id_value uuid default null,
  session_token_value text default null,
  activity_discount_check_id_value text default null,
  company_slug_value text default null,
  product_type_id_value bigint default null
)
returns table (
  id bigint,
  name text,
  icon text,
  color text,
  default_duration integer,
  base_price numeric,
  active boolean,
  activity_discount_check_id text,
  product_type_id bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_name text := nullif(trim(coalesce(name_value, '')), '');
  clean_color text := coalesce(nullif(trim(coalesce(color_value, '')), ''), '#42A5F5');
  clean_duration integer := coalesce(default_duration_value, 30);
  clean_base_price numeric := coalesce(base_price_value, 0);
  clean_activity_discount_check_id text := nullif(trim(coalesce(activity_discount_check_id_value, '')), '');
  clean_product_type_id bigint := product_type_id_value;
  admin_account public.internal_accounts%rowtype;
  target_company_id uuid;
  is_pedido_mode boolean := false;
begin
  admin_account := public.validate_internal_session(account_id_value, session_token_value, 'admin'::public.app_role);
  target_company_id := coalesce(public.get_company_id_by_slug(company_slug_value), admin_account.company_id);

  if target_company_id is null then
    raise exception 'La empresa no esta disponible.';
  end if;

  if admin_account.company_id is distinct from target_company_id then
    raise exception 'No podes administrar otra empresa.';
  end if;

  select (
    coalesce(config.modo_operacion, 'turno') = 'pedido'
    or config.usa_agenda = false
  )
  into is_pedido_mode
  from public.app_configuration config
  where config.company_id = target_company_id
  limit 1;

  if clean_name is null then
    raise exception 'Ingresa el nombre del servicio.';
  end if;

  if clean_duration <= 0 then
    raise exception 'La duracion del servicio debe ser mayor a cero.';
  end if;

  if clean_base_price < 0 then
    raise exception 'El precio base no puede ser negativo.';
  end if;

  if clean_product_type_id is not null then
    if not exists (
      select 1
      from public.product_types
      where product_types.id = clean_product_type_id
        and product_types.company_id = target_company_id
    ) then
      raise exception 'El tipo de producto no pertenece a esta empresa.';
    end if;
  end if;

  if not is_pedido_mode then
    clean_product_type_id := null;
  end if;

  if service_id_value is null then
    return query
    insert into public.services (
      company_id,
      name,
      icon,
      color,
      default_duration,
      base_price,
      active,
      activity_discount_check_id,
      product_type_id
    )
    values (
      target_company_id,
      clean_name,
      nullif(trim(coalesce(icon_value, '')), ''),
      clean_color,
      clean_duration,
      clean_base_price,
      coalesce(active_value, true),
      clean_activity_discount_check_id,
      clean_product_type_id
    )
    returning
      services.id,
      services.name,
      services.icon,
      services.color,
      services.default_duration,
      services.base_price,
      services.active,
      services.activity_discount_check_id,
      services.product_type_id;

    return;
  end if;

  return query
  update public.services
  set name = clean_name,
      icon = nullif(trim(coalesce(icon_value, '')), ''),
      color = clean_color,
      default_duration = clean_duration,
      base_price = clean_base_price,
      active = coalesce(active_value, true),
      activity_discount_check_id = clean_activity_discount_check_id,
      product_type_id = clean_product_type_id,
      company_id = target_company_id
  where services.id = service_id_value
    and services.company_id = target_company_id
  returning
    services.id,
    services.name,
    services.icon,
    services.color,
    services.default_duration,
    services.base_price,
    services.active,
    services.activity_discount_check_id,
    services.product_type_id;

  if not found then
    raise exception 'El servicio no pertenece a esta empresa.';
  end if;
end;
$$;

revoke execute on function public.get_admin_product_types(uuid, text, text) from public;
revoke execute on function public.save_admin_product_type(bigint, text, boolean, uuid, text, text) from public;
revoke execute on function public.delete_admin_product_type(bigint, uuid, text, text) from public;
revoke execute on function public.save_admin_service(bigint, text, text, text, integer, numeric, boolean, uuid, text, text, text, bigint) from public;

grant execute on function public.get_admin_product_types(uuid, text, text) to anon, authenticated;
grant execute on function public.save_admin_product_type(bigint, text, boolean, uuid, text, text) to anon, authenticated;
grant execute on function public.delete_admin_product_type(bigint, uuid, text, text) to anon, authenticated;
grant execute on function public.save_admin_service(bigint, text, text, text, integer, numeric, boolean, uuid, text, text, text, bigint) to anon, authenticated;

commit;
